export default {
    locationsUsuario: [
        {title:0, direccion: '9170125 Santiago, Santiago / Estación Central, Región Metropolitana', cordenadas : [-33.4500664, -70.686449]},
        {title:1, direccion: 'Avda Libertador Bernardo O`Higgins 1315, Santiago, 8340658, Región Metropolitana', cordenadas : [-33.4444012,-70.6555231]},
        {title:2, direccion: 'Nueva Los Leones 71, Providencia, Región Metropolitana', cordenadas : [-33.4192201,-70.6091028]}
      ],
      locationsFarmacias:[
        {
      id: 1,
      name: 'Salcobrand Maipú',
      coordinates: [-33.516105, -70.764565],
      address: 'Av. Pajaritos 2345, Maipú, Santiago',
      favorito: false,
      disponible: false,
      distancia: 1,
    },
    {
      id: 2,
      name: 'Cruz Verde Ñuñoa',
      coordinates: [-33.464208, -70.598943],
      address: 'Av. Irarrázaval 3456, Ñuñoa, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 3,
      name: 'Ahumada Providencia',
      coordinates: [-33.431502, -70.608578],
      address: 'Av. Providencia 7890, Providencia, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 4,
      name: 'Dr. Simi Santiago Centro',
      coordinates: [-33.439280, -70.651250],
      address: 'Calle Moneda 120, Santiago Centro, Santiago',
      favorito: false,
      disponible: false,
      distancia: 0,
    },
    {
      id: 5,
      name: 'Dr. Ahorro Las Condes',
      coordinates: [-33.409670, -70.570488],
      address: 'Av. Las Condes 987, Las Condes, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 6,
      name: 'Salcobrand La Cisterna',
      coordinates: [-33.538275, -70.655815],
      address: 'Av. Américo Vespucio 876, La Cisterna, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 7,
      name: 'Cruz Verde Las Condes',
      coordinates: [-33.412895, -70.548771],
      address: 'Av. Las Condes 4321, Las Condes, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 8,
      name: 'Ahumada Ñuñoa',
      coordinates: [-33.458216, -70.619556],
      address: 'Av. Irarrázaval 6789, Ñuñoa, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 9,
      name: 'Dr. Simi Vitacura',
      coordinates: [-33.395951, -70.576219],
      address: 'Av. Vitacura 5678, Vitacura, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 10,
      name: 'Dr. Ahorro Providencia',
      coordinates: [-33.432875, -70.607934],
      address: 'Av. Providencia 4321, Providencia, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 11,
      name: 'Salcobrand La Florida',
      coordinates: [-33.531927, -70.582781],
      address: 'Av. La Florida 2345, La Florida, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 12,
      name: 'Cruz Verde Peñalolén',
      coordinates: [-33.485219, -70.517148],
      address: 'Av. Grecia 1234, Peñalolén, Santiago',
      favorito: false,
      disponible: false,
      distancia: 0,
    },
    {
      id: 13,
      name: 'Ahumada Santiago Centro',
      coordinates: [-33.440709, -70.664211],
      address: 'Calle Huérfanos 789, Santiago Centro, Santiago',
      favorito: true,
      disponible: true,
      distancia: 0,
    },
    {
      id: 14,
      name: 'Dr. Simi Las Condes',
      coordinates: [-33.415862, -70.565883],
      address: 'Av. Las Condes 5678, Las Condes, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 15,
      name: 'Dr. Ahorro Maipú',
      coordinates: [-33.521714, -70.763925],
      address: 'Av. Pajaritos 4321, Maipú, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 16,
      name: 'Salcobrand Ñuñoa',
      coordinates: [-33.451663, -70.593092],
      address: 'Av. Irarrázaval 2345, Ñuñoa, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 17,
      name: 'Cruz Verde La Cisterna',
      coordinates: [-33.541628, -70.664276],
      address: 'Av. Américo Vespucio 4321, La Cisterna, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 18,
      name: 'Ahumada Las Condes',
      coordinates: [-33.413540, -70.567701],
      address: 'Av. Las Condes 6789, Las Condes, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 19,
      name: 'Dr. Simi Ñuñoa',
      coordinates: [-33.454269, -70.618902],
      address: 'Av. Irarrázaval 1234, Ñuñoa, Santiago',
      favorito: false,
      disponible: false,
      distancia: 0,
    },
    {
      id: 20,
      name: 'Dr. Ahorro Las Condes',
      coordinates: [-33.412457, -70.569187],
      address: 'Av. Las Condes 8765, Las Condes, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 21,
      name: 'Knop Las Condes',
      coordinates: [-33.413725, -70.565104],
      address: 'Av. Las Condes 8765, Las Condes, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 22,
      name: 'Belén Ñuñoa',
      coordinates: [-33.460785, -70.626865],
      address: 'Av. Irarrázaval 7890, Ñuñoa, Santiago',
      favorito: false,
      disponible: false,
      distancia: 0,
    },
    {
      id: 23,
      name: 'La Botika La Cisterna',
      coordinates: [-33.540294, -70.662077],
      address: 'Av. Américo Vespucio 6789, La Cisterna, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 24,
      name: 'Galénica Las Condes',
      coordinates: [-33.409765, -70.564995],
      address: 'Av. Las Condes 3456, Las Condes, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 25,
      name: 'Salcobrand Providencia',
      coordinates: [-33.432503, -70.609647],
      address: 'Av. Providencia 3456, Providencia, Santiago',
      favorito: false,
      disponible: false,
      distancia: 0,
    },
    {
      id: 26,
      name: 'Cruz Verde Maipú',
      coordinates: [-33.517148, -70.770171],
      address: 'Av. Pajaritos 7890, Maipú, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 27,
      name: 'Ahumada Ñuñoa',
      coordinates: [-33.464351, -70.600825],
      address: 'Av. Irarrázaval 8765, Ñuñoa, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 28,
      name: 'Dr. Simi Santiago Centro',
      coordinates: [-33.445179, -70.652442],
      address: 'Calle Moneda 876, Santiago Centro, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 29,
      name: 'Dr. Ahorro Las Condes',
      coordinates: [-33.412284, -70.570894],
      address: 'Av. Las Condes 3456, Las Condes, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 30,
      name: 'Salcobrand Providencia',
      coordinates: [-33.4248404, -70.6252382],
      address: 'Av. Providencia 3456, Providencia, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 31,
      name: 'Salcobrand Estación Central',
      coordinates: [-33.456749, -70.703411],
      address: 'Av. Libertador Bernardo O\'Higgins 4567, Estación Central, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 32,
      name: 'Cruz Verde Quinta Normal',
      coordinates: [-33.423948, -70.699080],
      address: 'Av. Carrascal 2345, Quinta Normal, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 33,
      name: 'Ahumada Estación Central',
      coordinates: [-33.459942, -70.708551],
      address: 'Av. Alameda 6789, Estación Central, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 34,
      name: 'Dr. Simi Quinta Normal',
      coordinates: [-33.428692, -70.703244],
      address: 'Av. Matucana 3456, Quinta Normal, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 35,
      name: 'Dr. Ahorro Estación Central',
      coordinates: [-33.459408, -70.709646],
      address: 'Av. Alameda 4321, Estación Central, Santiago',
      favorito: false,
      disponible: false,
      distancia: 0,
    },
    {
      id: 36,
      name: 'Salcobrand Quinta Normal',
      coordinates: [-33.432274, -70.692274],
      address: 'Av. Carrascal 6789, Quinta Normal, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 37,
      name: 'Cruz Verde Estación Central',
      coordinates: [-33.456587, -70.705789],
      address: 'Av. Libertador Bernardo O\'Higgins 9876, Estación Central, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 38,
      name: 'Ahumada Quinta Normal',
      coordinates: [-33.430762, -70.697715],
      address: 'Av. Carrascal 1234, Quinta Normal, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 39,
      name: 'Dr. Simi Estación Central',
      coordinates: [-33.456184, -70.707214],
      address: 'Av. Libertador Bernardo O\'Higgins 2345, Estación Central, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 40,
      name: 'Dr. Ahorro Quinta Normal',
      coordinates: [-33.427613, -70.695922],
      address: 'Av. Matucana 6789, Quinta Normal, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 41,
      name: 'Salcobrand Maipú',
      coordinates: [-33.516105, -70.764565],
      address: 'Av. Pajaritos 2345, Maipú, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 42,
      name: 'Cruz Verde Ñuñoa',
      coordinates: [-33.464208, -70.598943],
      address: 'Av. Irarrázaval 3456, Ñuñoa, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 43,
      name: 'Ahumada Providencia',
      coordinates: [-33.431502, -70.608578],
      address: 'Av. Providencia 7890, Providencia, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 44,
      name: 'Dr. Simi Santiago Centro',
      coordinates: [-33.454456, -70.661288],
      address: 'Calle Moneda 120, Santiago Centro, Santiago',
      favorito: false,
      disponible: false,
      distancia: 0,
    },
    {
      id: 45,
      name: 'Dr. Ahorro Las Condes',
      coordinates: [-33.409670, -70.570488],
      address: 'Av. Las Condes 987, Las Condes, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 46,
      name: 'Salcobrand La Cisterna',
      coordinates: [-33.538275, -70.655815],
      address: 'Av. Américo Vespucio 876, La Cisterna, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 47,
      name: 'Cruz Verde Las Condes',
      coordinates: [-33.412895, -70.548771],
      address: 'Av. Las Condes 4321, Las Condes, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 48,
      name: 'Ahumada Ñuñoa',
      coordinates: [-33.458216, -70.619556],
      address: 'Av. Irarrázaval 6789, Ñuñoa, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 49,
      name: 'Dr. Simi Vitacura',
      coordinates: [-33.395951, -70.576219],
      address: 'Av. Vitacura 5678, Vitacura, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 50,
      name: 'Dr. Ahorro Providencia',
      coordinates: [-33.432875, -70.607934],
      address: 'Av. Providencia 4321, Providencia, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 51,
      name: 'Salcobrand La Florida',
      coordinates: [-33.531927, -70.582781],
      address: 'Av. La Florida 2345, La Florida, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 52,
      name: 'Cruz Verde Peñalolén',
      coordinates: [-33.485219, -70.517148],
      address: 'Av. Grecia 1234, Peñalolén, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 53,
      name: 'Ahumada Santiago Centro',
      coordinates: [-33.433630, -70.662778],
      address: 'Calle Huérfanos 789, Santiago Centro, Santiago',
      favorito: false,
      disponible: false,
      distancia: 0,
    },
    {
      id: 54,
      name: 'Dr. Simi Las Condes',
      coordinates: [-33.415862, -70.565883],
      address: 'Av. Las Condes 5678, Las Condes, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 55,
      name: 'Dr. Ahorro Maipú',
      coordinates: [-33.521714, -70.763925],
      address: 'Av. Pajaritos 4321, Maipú, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 56,
      name: 'Salcobrand Ñuñoa',
      coordinates: [-33.460612, -70.608778],
      address: 'Av. Irarrázaval 2345, Ñuñoa, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 57,
      name: 'Cruz Verde La Cisterna',
      coordinates: [-33.541628, -70.664276],
      address: 'Av. Américo Vespucio 4321, La Cisterna, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 58,
      name: 'Ahumada Las Condes',
      coordinates: [-33.413540, -70.567701],
      address: 'Av. Las Condes 6789, Las Condes, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 59,
      name: 'Dr. Simi Ñuñoa',
      coordinates: [-33.454269, -70.618902],
      address: 'Av. Irarrázaval 1234, Ñuñoa, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 60,
      name: 'Dr. Ahorro Las Condes',
      coordinates: [-33.412457, -70.569187],
      address: 'Av. Las Condes 8765, Las Condes, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 61,
      name: 'Knop Las Condes',
      coordinates: [-33.413725, -70.565104],
      address: 'Av. Las Condes 8765, Las Condes, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 62,
      name: 'Belén Ñuñoa',
      coordinates: [-33.461117, -70.600156],
      address: 'Av. Irarrázaval 7890, Ñuñoa, Santiago',
      favorito: false,
      disponible: false,
      distancia: 0,
    },
    {
      id: 63,
      name: 'La Botika La Cisterna',
      coordinates: [-33.540294, -70.662077],
      address: 'Av. Américo Vespucio 6789, La Cisterna, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 64,
      name: 'Galénica Las Condes',
      coordinates: [-33.409765, -70.564995],
      address: 'Av. Las Condes 3456, Las Condes, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 65,
      name: 'Salcobrand Providencia',
      coordinates: [-33.4360512, -70.6239643],
      address: 'Av. Providencia 3456, Providencia, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 66,
      name: 'Cruz Verde Maipú',
      coordinates: [-33.517148, -70.770171],
      address: 'Av. Pajaritos 7890, Maipú, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 67,
      name: 'Ahumada Ñuñoa',
      coordinates: [-33.464351, -70.600825],
      address: 'Av. Irarrázaval 8765, Ñuñoa, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 68,
      name: 'Dr. Simi Santiago Centro',
      coordinates: [-33.4405643, -70.6577449],
      address: 'Calle Moneda 876, Santiago Centro, Santiago',
      favorito: false,
      disponible: false,
      distancia: 0,
    },
    {
      id: 69,
      name: 'Dr. Ahorro Las Condes',
      coordinates: [-33.412284, -70.570894],
      address: 'Av. Las Condes 3456, Las Condes, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
    {
      id: 70,
      name: 'Salcobrand Providencia',
      coordinates: [-33.427247, -70.5959526],
      address: 'Av. Providencia 3456, Providencia, Santiago',
      favorito: false,
      disponible: true,
      distancia: 0,
    },
      ], // array con locaciones de farmacias
      locationsCentros:[
      {
      id: 31,
      name: 'SAPU Providencia',
      coordinates: [-33.4615456, -70.6763792],
      address: 'Av. Providencia 321',
      aforo: 15,
      aforoC1: 2,
      aforoC2: 5,
      aforoC3: 1,
      aforoC4: 6,
      aforoC5: 1,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 32,
      name: 'CESFAM Santiago Centro',
      coordinates: [-33.4692897, -70.6863032],
      address: 'Calle Moneda 789',
      aforo: 8,
      aforoC1: 1,
      aforoC2: 3,
      aforoC3: 2,
      aforoC4: 1,
      aforoC5: 1,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 33,
      name: 'Hospital Providencia',
      coordinates: [-33.4598932, -70.6682721],
      address: 'Av. Los Conquistadores 1010',
      aforo: 12,
      aforoC1: 3,
      aforoC2: 2,
      aforoC3: 3,
      aforoC4: 2,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 34,
      name: 'Clínica Los Leones',
      coordinates: [-33.4685179, -70.6586723],
      address: 'Calle Los Héroes 2020',
      aforo: 5,
      aforoC1: 0,
      aforoC2: 1,
      aforoC3: 2,
      aforoC4: 1,
      aforoC5: 1,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 35,
      name: 'Centro de Urgencias Ñuñoa',
      coordinates: [-33.4667821, -70.7002675],
      address: 'Av. Ñuñoa 1212',
      aforo: 10,
      aforoC1: 1,
      aforoC2: 2,
      aforoC3: 3,
      aforoC4: 2,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 36,
      name: 'Hospital La Cisterna',
      coordinates: [-33.4679935, -70.6957391],
      address: 'Calle Providencia 333',
      aforo: 18,
      aforoC1: 2,
      aforoC2: 4,
      aforoC3: 6,
      aforoC4: 2,
      aforoC5: 4,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 37,
      name: 'Hospital Los Álamos',
      coordinates: [-33.4632264, -70.6792209],
      address: 'Av. Lyon 456',
      aforo: 25,
      aforoC1: 5,
      aforoC2: 4,
      aforoC3: 5,
      aforoC4: 6,
      aforoC5: 5,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 38,
      name: 'Hospital La Florida',
      coordinates: [-33.474893, -70.596738],
      address: 'Av. La Florida 333',
      aforo: 14,
      aforoC1: 2,
      aforoC2: 3,
      aforoC3: 3,
      aforoC4: 3,
      aforoC5: 3,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 39,
      name: 'CESFAM San Carlos',
      coordinates: [-33.4893291, -70.6427623],
      address: 'Calle San Carlos 222',
      aforo: 20,
      aforoC1: 4,
      aforoC2: 3,
      aforoC3: 5,
      aforoC4: 4,
      aforoC5: 4,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 40,
      name: 'SAPU La Reina',
      coordinates: [-33.4576264, -70.5472209],
      address: 'Av. La Reina 567',
      aforo: 13,
      aforoC1: 3,
      aforoC2: 2,
      aforoC3: 3,
      aforoC4: 2,
      aforoC5: 3,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 41,
      name: 'Clínica Santiago Oriente',
      coordinates: [-33.469999, -70.676839],
      address: 'Calle Salvador 555',
      aforo: 10,
      aforoC1: 2,
      aforoC2: 3,
      aforoC3: 1,
      aforoC4: 2,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 42,
      name: 'Hospital Santa Lucía',
      coordinates: [-33.4809935, -70.6797391],
      address: 'Av. Santa Lucía 333',
      aforo: 15,
      aforoC1: 3,
      aforoC2: 2,
      aforoC3: 4,
      aforoC4: 3,
      aforoC5: 3,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 43,
      name: 'SAPU Ñuñoa',
      coordinates: [-33.4579935, -70.6187391],
      address: 'Av. Ñuñoa 1212',
      aforo: 8,
      aforoC1: 2,
      aforoC2: 1,
      aforoC3: 2,
      aforoC4: 1,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 44,
      name: 'CESFAM San Miguel',
      coordinates: [-33.4893291, -70.6407623],
      address: 'Calle San Miguel 222',
      aforo: 16,
      aforoC1: 4,
      aforoC2: 3,
      aforoC3: 3,
      aforoC4: 4,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 45,
      name: 'Hospital La Cisterna Sur',
      coordinates: [-33.4658932, -70.6602721],
      address: 'Calle Los Héroes 3030',
      aforo: 22,
      aforoC1: 5,
      aforoC2: 4,
      aforoC3: 6,
      aforoC4: 4,
      aforoC5: 3,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 46,
      name: 'Clínica Providencia',
      coordinates: [-33.469993, -70.622839],
      address: 'Av. Providencia 888',
      aforo: 11,
      aforoC1: 1,
      aforoC2: 3,
      aforoC3: 3,
      aforoC4: 2,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 47,
      name: 'Centro de Urgencias Las Condes',
      coordinates: [-33.4152291, -70.5940623],
      address: 'Calle Las Condes 444',
      aforo: 9,
      aforoC1: 2,
      aforoC2: 1,
      aforoC3: 2,
      aforoC4: 2,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 48,
      name: 'Hospital Los Alpes',
      coordinates: [-33.4168103, -70.6107391],
      address: 'Av. Los Alpes 333',
      aforo: 10,
      aforoC1: 3,
      aforoC2: 2,
      aforoC3: 2,
      aforoC4: 1,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 49,
      name: 'SAPU Macul',
      coordinates: [-33.4763291, -70.6060623],
      address: 'Calle Macul 777',
      aforo: 12,
      aforoC1: 2,
      aforoC2: 2,
      aforoC3: 3,
      aforoC4: 2,
      aforoC5: 3,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 50,
      name: 'CESFAM La Florida',
      coordinates: [-33.488893, -70.590738],
      address: 'Av. La Florida 999',
      aforo: 17,
      aforoC1: 3,
      aforoC2: 4,
      aforoC3: 5,
      aforoC4: 3,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 51,
      name: 'Hospital San Joaquín',
      coordinates: [-33.4729935, -70.6207391],
      address: 'Calle San Joaquín 1234',
      aforo: 13,
      aforoC1: 2,
      aforoC2: 2,
      aforoC3: 4,
      aforoC4: 2,
      aforoC5: 3,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 52,
      name: 'Clínica El Bosque',
      coordinates: [-33.435993, -70.641738],
      address: 'Av. El Bosque 777',
      aforo: 20,
      aforoC1: 4,
      aforoC2: 3,
      aforoC3: 5,
      aforoC4: 4,
      aforoC5: 4,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 53,
      name: 'SAPU San Miguel',
      coordinates: [-33.4953291, -70.6550623],
      address: 'Calle San Miguel 555',
      aforo: 9,
      aforoC1: 2,
      aforoC2: 1,
      aforoC3: 3,
      aforoC4: 2,
      aforoC5: 1,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 54,
      name: 'CESFAM Ñuñoa',
      coordinates: [-33.4508935, -70.6227391],
      address: 'Av. Ñuñoa 787',
      aforo: 11,
      aforoC1: 2,
      aforoC2: 3,
      aforoC3: 2,
      aforoC4: 3,
      aforoC5: 1,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 55,
      name: 'Hospital Santiago Sur',
      coordinates: [-33.4809935, -70.6607391],
      address: 'Calle Santa Rosa 555',
      aforo: 13,
      aforoC1: 3,
      aforoC2: 3,
      aforoC3: 2,
      aforoC4: 2,
      aforoC5: 3,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 56,
      name: 'Clínica Las Condes',
      coordinates: [-33.4209935, -70.6107391],
      address: 'Av. Las Condes 111',
      aforo: 14,
      aforoC1: 3,
      aforoC2: 3,
      aforoC3: 2,
      aforoC4: 2,
      aforoC5: 4,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 57,
      name: 'Centro de Urgencias Macul',
      coordinates: [-33.477999, -70.610738],
      address: 'Av. Macul 222',
      aforo: 10,
      aforoC1: 2,
      aforoC2: 2,
      aforoC3: 2,
      aforoC4: 2,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 58,
      name: 'Hospital San Joaquín Norte',
      coordinates: [-33.4729935, -70.6137391],
      address: 'Calle San Joaquín 555',
      aforo: 16,
      aforoC1: 3,
      aforoC2: 3,
      aforoC3: 4,
      aforoC4: 3,
      aforoC5: 3,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 59,
      name: 'Clínica Santa Rosa',
      coordinates: [-33.4648893, -70.6362623],
      address: 'Av. Santa Rosa 123',
      aforo: 12,
      aforoC1: 2,
      aforoC2: 2,
      aforoC3: 3,
      aforoC4: 3,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 60,
      name: 'SAPU Pedro de Valdivia',
      coordinates: [-33.4309935, -70.617738],
      address: 'Av. Pedro de Valdivia 555',
      aforo: 14,
      aforoC1: 2,
      aforoC2: 3,
      aforoC3: 4,
      aforoC4: 2,
      aforoC5: 3,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 61,
      name: 'SAPU Lo Prado',
      coordinates: [-33.4459935, -70.7057381],
      address: 'Av. Lo Prado 555',
      aforo: 11,
      aforoC1: 2,
      aforoC2: 2,
      aforoC3: 4,
      aforoC4: 2,
      aforoC5: 1,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: true,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 62,
      name: 'CESFAM San Ramón',
      coordinates: [-33.5369935, -70.633738],
      address: 'Calle San Ramón 333',
      aforo: 15,
      aforoC1: 3,
      aforoC2: 2,
      aforoC3: 4,
      aforoC4: 3,
      aforoC5: 3,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 63,
      name: 'Hospital Padre Hurtado',
      coordinates: [-33.5029935, -70.590738],
      address: 'Av. Padre Hurtado 777',
      aforo: 20,
      aforoC1: 4,
      aforoC2: 4,
      aforoC3: 4,
      aforoC4: 4,
      aforoC5: 4,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 64,
      name: 'SAPU San Bernardo',
      coordinates: [-33.5909935, -70.706738],
      address: 'Av. San Bernardo 111',
      aforo: 12,
      aforoC1: 2,
      aforoC2: 2,
      aforoC3: 4,
      aforoC4: 2,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 65,
      name: 'Hospital La Granja',
      coordinates: [-33.5359935, -70.621738],
      address: 'Av. La Granja 888',
      aforo: 18,
      aforoC1: 4,
      aforoC2: 3,
      aforoC3: 5,
      aforoC4: 3,
      aforoC5: 3,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 66,
      name: 'CESFAM La Cisterna',
      coordinates: [-33.5329935, -70.662738],
      address: 'Calle La Cisterna 777',
      aforo: 15,
      aforoC1: 2,
      aforoC2: 3,
      aforoC3: 4,
      aforoC4: 3,
      aforoC5: 3,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 67,
      name: 'SAPU Puente Alto',
      coordinates: [-33.6189935, -70.586738],
      address: 'Av. Puente Alto 555',
      aforo: 10,
      aforoC1: 2,
      aforoC2: 2,
      aforoC3: 3,
      aforoC4: 1,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 68,
      name: 'Clínica San Ramón',
      coordinates: [-33.5319935, -70.641738],
      address: 'Av. San Ramón 333',
      aforo: 12,
      aforoC1: 2,
      aforoC2: 3,
      aforoC3: 2,
      aforoC4: 3,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 69,
      name: 'Hospital Macul',
      coordinates: [-33.4919935, -70.595738],
      address: 'Av. Macul 444',
      aforo: 14,
      aforoC1: 3,
      aforoC2: 3,
      aforoC3: 2,
      aforoC4: 2,
      aforoC5: 4,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 70,
      name: 'CESFAM San Ramón Sur',
      coordinates: [-33.5399935, -70.625738],
      address: 'Calle San Ramón 666',
      aforo: 17,
      aforoC1: 4,
      aforoC2: 4,
      aforoC3: 4,
      aforoC4: 3,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 71,
      name: 'SAPU Puente Alto Sur',
      coordinates: [-33.6399935, -70.586738],
      address: 'Av. Puente Alto 777',
      aforo: 11,
      aforoC1: 2,
      aforoC2: 2,
      aforoC3: 3,
      aforoC4: 2,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 72,
      name: 'Hospital La Pintana',
      coordinates: [-33.6029935, -70.638738],
      address: 'Av. La Pintana 555',
      aforo: 13,
      aforoC1: 2,
      aforoC2: 3,
      aforoC3: 2,
      aforoC4: 3,
      aforoC5: 3,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 73,
      name: 'Clínica La Granja',
      coordinates: [-33.5289935, -70.635738],
      address: 'Av. La Granja 222',
      aforo: 9,
      aforoC1: 2,
      aforoC2: 1,
      aforoC3: 3,
      aforoC4: 1,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 74,
      name: 'SAPU La Granja',
      coordinates: [-33.5369935, -70.642738],
      address: 'Av. La Granja 333',
      aforo: 10,
      aforoC1: 2,
      aforoC2: 2,
      aforoC3: 2,
      aforoC4: 2,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 75,
      name: 'Hospital San Bernardo',
      coordinates: [-33.6089935, -70.708738],
      address: 'Av. San Bernardo 222',
      aforo: 16,
      aforoC1: 3,
      aforoC2: 3,
      aforoC3: 4,
      aforoC4: 3,
      aforoC5: 3,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 76,
      name: 'CESFAM San Bernardo',
      coordinates: [-33.5889935, -70.670738],
      address: 'Calle San Bernardo 444',
      aforo: 12,
      aforoC1: 2,
      aforoC2: 3,
      aforoC3: 2,
      aforoC4: 3,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 77,
      name: 'SAPU La Pintana',
      coordinates: [-33.6069935, -70.645738],
      address: 'Av. La Pintana 333',
      aforo: 14,
      aforoC1: 3,
      aforoC2: 2,
      aforoC3: 4,
      aforoC4: 3,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 78,
      name: 'Hospital Puente Alto',
      coordinates: [-33.6209935, -70.574738],
      address: 'Av. Puente Alto 111',
      aforo: 15,
      aforoC1: 3,
      aforoC2: 3,
      aforoC3: 4,
      aforoC4: 3,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 79,
      name: 'Clínica Puente Alto',
      coordinates: [-33.6129935, -70.579738],
      address: 'Av. Puente Alto 222',
      aforo: 10,
      aforoC1: 2,
      aforoC2: 2,
      aforoC3: 2,
      aforoC4: 2,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 80,
      name: 'SAPU El Bosque',
      coordinates: [-33.5629935, -70.676738],
      address: 'Av. El Bosque 333',
      aforo: 11,
      aforoC1: 2,
      aforoC2: 2,
      aforoC3: 3,
      aforoC4: 2,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 81,
      name: 'Hospital El Bosque',
      coordinates: [-33.5589935, -70.679738],
      address: 'Av. El Bosque 444',
      aforo: 12,
      aforoC1: 2,
      aforoC2: 3,
      aforoC3: 3,
      aforoC4: 2,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 82,
      name: 'CESFAM El Bosque',
      coordinates: [-33.5649935, -70.686738],
      address: 'Calle El Bosque 555',
      aforo: 10,
      aforoC1: 2,
      aforoC2: 2,
      aforoC3: 2,
      aforoC4: 2,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 83,
      name: 'SAPU San Ramón',
      coordinates: [-33.5369935, -70.639738],
      address: 'Av. San Ramón 333',
      aforo: 13,
      aforoC1: 3,
      aforoC2: 2,
      aforoC3: 3,
      aforoC4: 3,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 84,
      name: 'CESFAM San Ramón',
      coordinates: [-33.5299935, -70.632738],
      address: 'Calle San Ramón 444',
      aforo: 12,
      aforoC1: 2,
      aforoC2: 2,
      aforoC3: 3,
      aforoC4: 2,
      aforoC5: 3,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 85,
      name: 'Hospital La Granja',
      coordinates: [-33.5389935, -70.630738],
      address: 'Av. La Granja 444',
      aforo: 15,
      aforoC1: 2,
      aforoC2: 3,
      aforoC3: 4,
      aforoC4: 3,
      aforoC5: 3,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 86,
      name: 'SAPU La Florida',
      coordinates: [-33.5609935, -70.584738],
      address: 'Av. La Florida 222',
      aforo: 12,
      aforoC1: 2,
      aforoC2: 3,
      aforoC3: 2,
      aforoC4: 3,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 87,
      name: 'Clínica La Florida',
      coordinates: [-33.5589935, -70.586738],
      address: 'Av. La Florida 333',
      aforo: 10,
      aforoC1: 2,
      aforoC2: 2,
      aforoC3: 2,
      aforoC4: 2,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: false,
      tiempoTotal: 0,
      distancia: 0,
    },
    {
      id: 88,
      name: 'Hospital San Ramón',
      coordinates: [-33.5349935, -70.637738],
      address: 'Av. San Ramón 555',
      aforo: 11,
      aforoC1: 2,
      aforoC2: 2,
      aforoC3: 3,
      aforoC4: 2,
      aforoC5: 2,
      tiempoC3: 0,
      tiempoC4: 0,
      tiempoC5: 0,
      favorito: false,
      disponible: true,
      tiempoTotal: 0,
      distancia: 0,
    },
      ],
      itemsMedicamentos: [
        {
          id: 1,
          favorito: true,
          medicamento: 'Paracetamol 80 mg x 16 Comprimidos Masticables',
          precio: '1000',
          laboratorio: 'Farmalab',
          receta: 'Sin receta',
        },
        {
          id: 2,
          favorito: true,
          medicamento: 'Ibuprofeno 200 mg x 20 Comprimidos Recubiertos',
          precio: '1500',
          laboratorio: 'MediPharma',
          receta: 'Sin receta',
        },
        {
          id: 3,
          favorito: false,
          medicamento: 'Omeprazol 20 mg x 14 Cápsulas',
          precio: '2000',
          laboratorio: 'SaludPlus',
          receta: 'Sin receta',
        },
        {
          id: 4,
          favorito: false,
          medicamento: 'Amoxicilina 500 mg x 12 Cápsulas',
          precio: '2500',
          laboratorio: 'BioGen',
          receta: 'Con receta',
        },
        {
          id: 5,
          favorito: false,
          medicamento: 'Aspirina 100 mg x 50 Tabletas',
          precio: '800',
          laboratorio: 'PharmaCorp',
          receta: 'Sin receta',
        },
        {
          id: 6,
          favorito: false,
          medicamento: 'Loratadina 10 mg x 30 Tabletas',
          precio: '1200',
          laboratorio: 'BioHealth',
          receta: 'Sin receta',
        },
        {
          id: 7,
          favorito: false,
          medicamento: 'Vitamina C 500 mg x 60 Comprimidos Efervescentes',
          precio: '1800',
          laboratorio: 'NutriVida',
          receta: 'Sin receta',
        },
        {
          id: 8,
          favorito: false,
          medicamento: 'Clorfenamina 4 mg x 24 Tabletas',
          precio: '900',
          laboratorio: 'MediVit',
          receta: 'Sin receta',
        },
        {
          id: 9,
          favorito: false,
          medicamento: 'Acetaminofén 500 mg x 30 Tabletas',
          precio: '1200',
          laboratorio: 'MediHealth',
          receta: 'Sin receta',
        },
        {
          id: 10,
          favorito: false,
          medicamento: 'Diclofenaco 50 mg x 20 Comprimidos',
          precio: '1400',
          laboratorio: 'Farmagen',
          receta: 'Sin receta',
        },
        {
          id: 11,
          favorito: false,
          medicamento: 'Cetirizina 10 mg x 30 Tabletas',
          precio: '1700',
          laboratorio: 'BioPharma',
          receta: 'Sin receta',
        },
        {
          id: 12,
          favorito: false,
          medicamento: 'Diazepam 5 mg x 20 Comprimidos',
          precio: '3000',
          laboratorio: 'MediCare',
          receta: 'Con receta',
        },
        {
          id: 13,
          favorito: false,
          medicamento: 'Ciprofloxacina 500 mg x 10 Tabletas',
          precio: '3200',
          laboratorio: 'PharmaVida',
          receta: 'Con receta',
        },
        {
          id: 14,
          favorito: false,
          medicamento: 'Metformina 850 mg x 60 Tabletas',
          precio: '1800',
          laboratorio: 'SaludGen',
          receta: 'Sin receta',
        },
        {
          id: 15,
          favorito: false,
          medicamento: 'Ondansetrón 8 mg x 5 Tabletas',
          precio: '2800',
          laboratorio: 'PharmaPlus',
          receta: 'Con receta',
        },
        {
          id: 16,
          favorito: false,
          medicamento: 'Paroxetina 20 mg x 30 Tabletas',
          precio: '2500',
          laboratorio: 'MediLab',
          receta: 'Con receta',
        },
        {
          id: 17,
          favorito: false,
          medicamento: 'Salbutamol 100 mcg x 200 Dosis Inhalador',
          precio: '1500',
          laboratorio: 'BioSalud',
          receta: 'Con receta',
        },
        {
          id: 18,
          favorito: false,
          medicamento: 'Simvastatina 20 mg x 30 Tabletas',
          precio: '3800',
          laboratorio: 'HealthCare',
          receta: 'Con receta',
        },
        {
          id: 19,
          favorito: false,
          medicamento: 'Metronidazol 500 mg x 20 Tabletas',
          precio: '1900',
          laboratorio: 'PharmaMed',
          receta: 'Sin receta',
        },
        {
          id: 20,
          favorito: false,
          medicamento: 'Dipirona 500 mg x 40 Tabletas',
          precio: '900',
          laboratorio: 'PharmaWell',
          receta: 'Sin receta',
        },
        {
          id: 21,
          favorito: false,
          medicamento: 'Levocetirizina 5 mg x 20 Comprimidos',
          precio: '1600',
          laboratorio: 'MediPharm',
          receta: 'Sin receta',
        },
        {
          id: 22,
          favorito: false,
          medicamento: 'Amlodipino 5 mg x 30 Tabletas',
          precio: '2500',
          laboratorio: 'HealthPlus',
          receta: 'Con receta',
        },
        {
          id: 23,
          favorito: false,
          medicamento: 'Losartán 50 mg x 28 Comprimidos',
          precio: '2700',
          laboratorio: 'MediCare',
          receta: 'Con receta',
        },
        {
          id: 24,
          favorito: false,
          medicamento: 'Atorvastatina 10 mg x 30 Tabletas',
          precio: '3200',
          laboratorio: 'PharmaGen',
          receta: 'Con receta',
        },
        {
          id: 25,
          favorito: false,
          medicamento: 'Sertralina 50 mg x 14 Cápsulas',
          precio: '1800',
          laboratorio: 'SaludPlus',
          receta: 'Con receta',
        },
        {
          id: 26,
          favorito: false,
          medicamento: 'Amitriptilina 25 mg x 20 Comprimidos',
          precio: '2200',
          laboratorio: 'MediHealth',
          receta: 'Con receta',
        },
        {
          id: 27,
          favorito: false,
          medicamento: 'Ciprofloxacina 250 mg x 20 Tabletas',
          precio: '2800',
          laboratorio: 'BioHealth',
          receta: 'Con receta',
        },
        {
          id: 28,
          favorito: false,
          medicamento: 'Furosemida 40 mg x 30 Comprimidos',
          precio: '1200',
          laboratorio: 'PharmaCorp',
          receta: 'Con receta',
        },
        {
          id: 29,
          favorito: false,
          medicamento: 'Lisinopril 10 mg x 28 Comprimidos',
          precio: '1800',
          laboratorio: 'MediVit',
          receta: 'Con receta',
        },
        {
          id: 30,
          favorito: false,
          medicamento: 'Ranitidina 150 mg x 20 Comprimidos',
          precio: '900',
          laboratorio: 'Farmagen',
          receta: 'Sin receta',
        },
        {
          id: 31,
          favorito: false,
          medicamento: 'Tamsulosina 0.4 mg x 30 Cápsulas',
          precio: '2600',
          laboratorio: 'BioPharma',
          receta: 'Con receta',
        },
        {
          id: 32,
          favorito: false,
          medicamento: 'Bromhexina 8 mg x 24 Tabletas',
          precio: '1400',
          laboratorio: 'MediLab',
          receta: 'Sin receta',
        },
        {
          id: 33,
          favorito: false,
          medicamento: 'Metoclopramida 10 mg x 20 Comprimidos',
          precio: '1100',
          laboratorio: 'PharmaVida',
          receta: 'Sin receta',
        },
        {
          id: 34,
          favorito: false,
          medicamento: 'Esomeprazol 40 mg x 14 Cápsulas',
          precio: '2900',
          laboratorio: 'SaludGen',
          receta: 'Con receta',
        },
        {
          id: 35,
          favorito: false,
          medicamento: 'Montelukast 10 mg x 30 Tabletas',
          precio: '2300',
          laboratorio: 'PharmaPlus',
          receta: 'Con receta',
        },
        {
          id: 36,
          favorito: false,
          medicamento: 'Fluconazol 150 mg x 1 Cápsula',
          precio: '1500',
          laboratorio: 'MediPharm',
          receta: 'Con receta',
        },
        {
          id: 37,
          favorito: false,
          medicamento: 'Enalapril 20 mg x 28 Comprimidos',
          precio: '1700',
          laboratorio: 'HealthPlus',
          receta: 'Con receta',
        },
        {
          id: 38,
          favorito: false,
          medicamento: 'Escitalopram 10 mg x 20 Comprimidos',
          precio: '1800',
          laboratorio: 'MediCare',
          receta: 'Con receta',
        },
        {
          id: 39,
          favorito: false,
          medicamento: 'Candesartán 8 mg x 30 Tabletas',
          precio: '2500',
          laboratorio: 'PharmaGen',
          receta: 'Con receta',
        },
        {
          id: 40,
          favorito: false,
          medicamento: 'Pregabalina 75 mg x 14 Cápsulas',
          precio: '3200',
          laboratorio: 'SaludPlus',
          receta: 'Con receta',
        },
        {
          id: 41,
          favorito: false,
          medicamento: 'Naproxeno 500 mg x 24 Tabletas',
          precio: '1600',
          laboratorio: 'MediHealth',
          receta: 'Sin receta',
        },
        {
          id: 42,
          favorito: false,
          medicamento: 'Risperidona 2 mg x 20 Tabletas',
          precio: '2200',
          laboratorio: 'BioHealth',
          receta: 'Con receta',
        },
        {
          id: 43,
          favorito: false,
          medicamento: 'Metamizol 500 mg x 30 Comprimidos',
          precio: '2800',
          laboratorio: 'PharmaCorp',
          receta: 'Sin receta',
        },
        {
          id: 44,
          favorito: false,
          medicamento: 'Doxorrubicina 50 mg x 1 Vial',
          precio: '1200',
          laboratorio: 'MediVit',
          receta: 'Con receta',
        },
        {
          id: 45,
          favorito: false,
          medicamento: 'Memantina 10 mg x 28 Comprimidos',
          precio: '1800',
          laboratorio: 'Farmagen',
          receta: 'Con receta',
        },
        {
          id: 46,
          favorito: false,
          medicamento: 'Bisacodilo 5 mg x 30 Comprimidos',
          precio: '900',
          laboratorio: 'BioPharma',
          receta: 'Sin receta',
        },
        {
          id: 47,
          favorito: false,
          medicamento: 'Prednisona 5 mg x 20 Tabletas',
          precio: '2600',
          laboratorio: 'MediLab',
          receta: 'Con receta',
        },
        {
          id: 48,
          favorito: false,
          medicamento: 'Amiodarona 200 mg x 30 Comprimidos',
          precio: '1400',
          laboratorio: 'PharmaVida',
          receta: 'Con receta',
        },
        {
          id: 49,
          favorito: false,
          medicamento: 'Ezetimiba 10 mg x 28 Comprimidos',
          precio: '1100',
          laboratorio: 'SaludGen',
          receta: 'Con receta',
        },
        {
          id: 50,
          favorito: false,
          medicamento: 'Fenilefrina 5 mg x 30 Tabletas',
          precio: '2300',
          laboratorio: 'PharmaPlus',
          receta: 'Sin receta',
        },
        {
          id: 51,
          favorito: false,
          medicamento: 'Metilprednisolona 16 mg x 10 Tabletas',
          precio: '1500',
          laboratorio: 'MediPharm',
          receta: 'Con receta',
        },
        {
          id: 52,
          favorito: false,
          medicamento: 'Codeína 30 mg x 20 Comprimidos',
          precio: '2700',
          laboratorio: 'HealthPlus',
          receta: 'Con receta',
        },
        {
          id: 53,
          favorito: false,
          medicamento: 'Bromuro de Pinaverio 100 mg x 40 Comprimidos',
          precio: '3200',
          laboratorio: 'MediCare',
          receta: 'Sin receta',
        },
        {
          id: 54,
          favorito: false,
          medicamento: 'Ciproterona 50 mg x 20 Tabletas',
          precio: '1800',
          laboratorio: 'PharmaGen',
          receta: 'Con receta',
        },
        {
          id: 55,
          favorito: false,
          medicamento: 'Clotrimazol 1% Crema x 20g',
          precio: '2500',
          laboratorio: 'SaludPlus',
          receta: 'Sin receta',
        },
        {
          id: 56,
          favorito: false,
          medicamento: 'Carbamazepina 200 mg x 30 Comprimidos',
          precio: '3200',
          laboratorio: 'BioHealth',
          receta: 'Con receta',
        },
        {
          id: 57,
          favorito: false,
          medicamento: 'Fentanilo 25 mcg/h Parche Transdérmico x 5',
          precio: '2600',
          laboratorio: 'PharmaCorp',
          receta: 'Con receta',
        },
        {
          id: 58,
          favorito: false,
          medicamento: 'Mometasona 0.1% Crema x 30g',
          precio: '1100',
          laboratorio: 'MediVit',
          receta: 'Con receta',
        },
        {
          id: 59,
          favorito: false,
          medicamento: 'Mebendazol 100 mg x 6 Tabletas',
          precio: '1500',
          laboratorio: 'Farmagen',
          receta: 'Sin receta',
        },
        {
          id: 60,
          favorito: false,
          medicamento: 'Glibenclamida 5 mg x 60 Tabletas',
          precio: '1700',
          laboratorio: 'BioPharma',
          receta: 'Con receta',
        },
        {
          id: 61,
          favorito: false,
          medicamento: 'Sulfato de Zinc 220 mg x 30 Tabletas',
          precio: '900',
          laboratorio: 'MediLab',
          receta: 'Sin receta',
        },
        {
          id: 62,
          favorito: false,
          medicamento: 'Vitamina B12 1000 mcg x 50 Tabletas',
          precio: '2200',
          laboratorio: 'PharmaVida',
          receta: 'Sin receta',
        },
        {
          id: 63,
          favorito: false,
          medicamento: 'Hidroclorotiazida 25 mg x 30 Comprimidos',
          precio: '1800',
          laboratorio: 'SaludGen',
          receta: 'Con receta',
        },
        {
          id: 64,
          favorito: false,
          medicamento: 'Dexametasona 4 mg x 20 Comprimidos',
          precio: '1900',
          laboratorio: 'PharmaPlus',
          receta: 'Con receta',
        },
        {
          id: 65,
          favorito: false,
          medicamento: 'Bupropion 150 mg x 30 Tabletas',
          precio: '2800',
          laboratorio: 'MediPharm',
          receta: 'Con receta',
        },
        {
          id: 66,
          favorito: false,
          medicamento: 'Ciclosporina 100 mg x 20 Cápsulas',
          precio: '3200',
          laboratorio: 'HealthPlus',
          receta: 'Con receta',
        },
        {
          id: 67,
          favorito: false,
          medicamento: 'Amantadina 100 mg x 30 Cápsulas',
          precio: '1200',
          laboratorio: 'MediCare',
          receta: 'Con receta',
        },
        {
          id: 68,
          favorito: false,
          medicamento: 'Dextrometorfano 15 mg x 20 Comprimidos',
          precio: '1500',
          laboratorio: 'PharmaGen',
          receta: 'Sin receta',
        },
        {
          id: 69,
          favorito: false,
          medicamento: 'Guaifenesina 200 mg x 30 Tabletas',
          precio: '1700',
          laboratorio: 'SaludPlus',
          receta: 'Sin receta',
        },
        {
          id: 70,
          favorito: false,
          medicamento: 'Rivastigmina 3 mg x 28 Cápsulas',
          precio: '2500',
          laboratorio: 'BioHealth',
          receta: 'Con receta',
        },
        {
          id: 71,
          favorito: false,
          medicamento: 'Lamotrigina 50 mg x 30 Comprimidos',
          precio: '3200',
          laboratorio: 'PharmaCorp',
          receta: 'Con receta',
        },
        {
          id: 72,
          favorito: false,
          medicamento: 'Hidroxizina 25 mg x 20 Comprimidos',
          precio: '1100',
          laboratorio: 'MediVit',
          receta: 'Sin receta',
        },
        {
          id: 73,
          favorito: false,
          medicamento: 'Biperideno 2 mg x 30 Tabletas',
          precio: '1500',
          laboratorio: 'Farmagen',
          receta: 'Con receta',
        },
        {
          id: 74,
          favorito: false,
          medicamento: 'Tolbutamida 500 mg x 60 Tabletas',
          precio: '1700',
          laboratorio: 'BioPharma',
          receta: 'Con receta',
        },
        {
          id: 75,
          favorito: false,
          medicamento: 'Loperamida 2 mg x 24 Cápsulas',
          precio: '900',
          laboratorio: 'MediLab',
          receta: 'Sin receta',
        },
        {
          id: 76,
          favorito: false,
          medicamento: 'Prometazina 25 mg x 20 Tabletas',
          precio: '2200',
          laboratorio: 'PharmaVida',
          receta: 'Sin receta',
        },
        {
          id: 77,
          favorito: false,
          medicamento: 'Propranolol 40 mg x 30 Comprimidos',
          precio: '1800',
          laboratorio: 'SaludGen',
          receta: 'Con receta',
        },
        {
          id: 78,
          favorito: false,
          medicamento: 'Bromuro de Potasio 600 mg x 50 Tabletas',
          precio: '1900',
          laboratorio: 'PharmaPlus',
          receta: 'Sin receta',
        },
        {
          id: 79,
          favorito: false,
          medicamento: 'Metilfenidato 10 mg x 30 Comprimidos',
          precio: '2800',
          laboratorio: 'MediPharm',
          receta: 'Con receta',
        },
        {
          id: 80,
          favorito: false,
          medicamento: 'Olanzapina 5 mg x 28 Comprimidos',
          precio: '3200',
          laboratorio: 'HealthPlus',
          receta: 'Con receta',
        },
        {
          id: 81,
          favorito: false,
          medicamento: 'Aceclofenaco 100 mg x 20 Comprimidos',
          precio: '1200',
          laboratorio: 'MediCare',
          receta: 'Con receta',
        },
        {
          id: 82,
          favorito: false,
          medicamento: 'Nitrofurantoína 100 mg x 30 Cápsulas',
          precio: '1500',
          laboratorio: 'PharmaGen',
          receta: 'Con receta',
        },
        {
          id: 83,
          favorito: false,
          medicamento: 'Fluticasona 50 mcg x 120 Dosis Inhalador',
          precio: '1700',
          laboratorio: 'SaludPlus',
          receta: 'Con receta',
        },
        {
          id: 84,
          favorito: false,
          medicamento: 'Lactulosa 10 g/15 ml Solución Oral x 200 ml',
          precio: '2500',
          laboratorio: 'BioHealth',
          receta: 'Sin receta',
        },
        {
          id: 85,
          favorito: false,
          medicamento: 'Dapoxetina 30 mg x 6 Tabletas',
          precio: '1100',
          laboratorio: 'PharmaCorp',
          receta: 'Con receta',
        },
        {
          id: 86,
          favorito: false,
          medicamento: 'Metilprednisolona 8 mg x 20 Comprimidos',
          precio: '1500',
          laboratorio: 'MediVit',
          receta: 'Con receta',
        },
        {
          id: 87,
          favorito: false,
          medicamento: 'Vitamina D3 1000 UI x 30 Cápsulas',
          precio: '900',
          laboratorio: 'Farmagen',
          receta: 'Sin receta',
        },
        {
          id: 88,
          favorito: false,
          medicamento: 'Terbinafina 250 mg x 28 Comprimidos',
          precio: '3200',
          laboratorio: 'BioPharma',
          receta: 'Con receta',
        },
        {
          id: 89,
          favorito: false,
          medicamento: 'Telmisartán 40 mg x 30 Tabletas',
          precio: '2200',
          laboratorio: 'MediLab',
          receta: 'Con receta',
        },
        {
          id: 90,
          favorito: false,
          medicamento: 'Nimesulida 100 mg x 30 Comprimidos',
          precio: '1500',
          laboratorio: 'PharmaVida',
          receta: 'Sin receta',
        },
        {
          id: 91,
          favorito: false,
          medicamento: 'Bromuro de Tiotropio 18 mcg x 30 Cápsulas',
          precio: '1800',
          laboratorio: 'SaludGen',
          receta: 'Con receta',
        },
        {
          id: 92,
          favorito: false,
          medicamento: 'Ácido Fólico 5 mg x 50 Tabletas',
          precio: '900',
          laboratorio: 'PharmaPlus',
          receta: 'Sin receta',
        },
        {
          id: 93,
          favorito: false,
          medicamento: 'Propiltiouracilo 50 mg x 50 Comprimidos',
          precio: '2800',
          laboratorio: 'MediPharm',
          receta: 'Con receta',
        },
        {
          id: 94,
          favorito: false,
          medicamento: 'Gliclazida 80 mg x 30 Tabletas',
          precio: '3200',
          laboratorio: 'HealthPlus',
          receta: 'Con receta',
        },
        {
          id: 95,
          favorito: false,
          medicamento: 'Ibuprofeno 400 mg x 10 Comprimidos',
          precio: '1200',
          laboratorio: 'MediCare',
          receta: 'Sin receta',
        },
        {
          id: 96,
          favorito: false,
          medicamento: 'Lorazepam 2 mg x 30 Comprimidos',
          precio: '1900',
          laboratorio: 'PharmaGen',
          receta: 'Con receta',
        },
        {
          id: 97,
          favorito: false,
          medicamento: 'Ácido Valproico 500 mg x 30 Comprimidos',
          precio: '2200',
          laboratorio: 'SaludPlus',
          receta: 'Con receta',
        },
        {
          id: 98,
          favorito: false,
          medicamento: 'Nifedipino 10 mg x 20 Cápsulas',
          precio: '2500',
          laboratorio: 'BioHealth',
          receta: 'Con receta',
        },
        {
          id: 99,
          favorito: false,
          medicamento: 'Tiopental Sódico 1 g Polvo para Solución Inyectable x 1 Vial',
          precio: '3200',
          laboratorio: 'PharmaCorp',
          receta: 'Con receta',
        },
        {
          id: 100,
          favorito: false,
          medicamento: 'Clotrimazol 100 mg x 6 Óvulos Vaginales',
          precio: '1100',
          laboratorio: 'MediVit',
          receta: 'Sin receta',
        },
        {
          id: 101,
          favorito: false,
          medicamento: 'Clonazepam 2 mg x 30 Comprimidos',
          precio: '2500',
          laboratorio: 'MediPharm',
          receta: 'Con receta',
        },
        {
          id: 102,
          favorito: false,
          medicamento: 'Ketoprofeno 100 mg x 20 Cápsulas',
          precio: '1800',
          laboratorio: 'SaludPlus',
          receta: 'Con receta',
        },
        {
          id: 103,
          favorito: false,
          medicamento: 'Domperidona 10 mg x 30 Tabletas',
          precio: '1200',
          laboratorio: 'PharmaGen',
          receta: 'Sin receta',
        },
        {
          id: 104,
          favorito: false,
          medicamento: 'Viadil (Loperamida + Simeticona) x 12 Comprimidos',
          precio: '1600',
          laboratorio: 'SaludPlus',
          receta: 'Sin receta',
        },
        {
          id: 105,
          favorito: false,
          medicamento: 'Ketorolaco 30 mg x 10 Tabletas',
          precio: '1800',
          laboratorio: 'MediPharm',
          receta: 'Con receta',
        },
        {
          id: 106,
          favorito: false,
          medicamento: 'Tramadol 50 mg x 20 Cápsulas',
          precio: '2000',
          laboratorio: 'PharmaCorp',
          receta: 'Con receta',
        },
        {
          id: 107,
          favorito: false,
          medicamento: 'Cefalmin (Acetaminofén + Cafeína) x 24 Tabletas',
          precio: '1500',
          laboratorio: 'MediPharm',
          receta: 'Sin receta',
        },
        {
          id: 108,
          favorito: false,
          medicamento: 'Ciclobenzaprina 10 mg x 20 Comprimidos',
          precio: '1800',
          laboratorio: 'SaludPlus',
          receta: 'Con receta',
        },
        {
          id: 109,
          favorito: false,
          medicamento: 'Desloratadina 5 mg x 10 Tabletas',
          precio: '1600',
          laboratorio: 'PharmaGen',
          receta: 'Sin receta',
        }
            // Puedes agregar más medicamentos aquí
      ],
  }